# Generated by Django 3.1.7 on 2022-12-21 00:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=50, validators=[django.core.validators.EmailValidator()]),
        ),
    ]
